#!/usr/bin/env bash

function build_index() {
    find -L . -type f -not -name '*\.*' -exec cat {} \; \
        | awk '{print length, $0}' \
        | sort -n \
        | cut -d " " -f2- \
        | tee index.txt
}
export -f build_index

find -L . -mindepth 1 -type d | xargs -n1 -I{} sh -c "cd {} && build_index"

ln -s default/index.txt index.txt

